name: release

on:
  push:
    branches:
      - master

defaults:
  run:
    shell: bash

permissions:
  pull-requests: write
  contents: write
  issues: write

jobs:
  publish-artifact:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v4

      - uses: cycjimmy/semantic-release-action@v4.0.0 # runs tests etc, publishes to private gh repo
        with:
          semantic_version: 18
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
